steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function_cicd
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python310
  - --allow-unauthenticated
  - --service-account=cicd-sa@gcp-devops-432119.iam.gserviceaccount.com

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - add-iam-policy-binding
  - function_cicd
  - --member=allUsers
  - --role=roles/cloudfunctions.invoker
  - --service-account=cicd-sa@gcp-devops-432119.iam.gserviceaccount.com

options:
  logging : CLOUD_LOGGING_ONLY
