steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function_cicd
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python310
  - --allow-unauthenticated

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - add-iam-policy-binding
  - function_cicd
  - --member=allUsers
  - --role=roles/cloudfunctions.invoker
